import button from "./documents/button";
import blockImages from "./documents/block-images";
import localization from "./documents/localization";
import richText from "./documents/rich-text";
import customPage from "./documents/custom-page";
import preDefinedPage from "./documents/pre-defined-pages";
import productCard from "./documents/product-card";
import localeString from "./documents/languages";
import cartItems from "./documents/cart-items";
import header from "./documents/header";
import cartIcon from "./documents/cartIcon";
import searchBar from "./documents/searchBar";
import footer from "./documents/footer";
import storeLogo from "./documents/storeLogo";
import menuItems from "./documents/menuItems";
import storeName from "./documents/store-name";
import plpData from "./documents/plp-data";
import pdpData from "./documents/pdp-data";
export const schemaTypes = [customPage,blockImages,richText,localization,button, preDefinedPage,productCard,localeString, cartItems,header,cartIcon,searchBar,footer, storeLogo, menuItems,storeName,plpData,pdpData]
