
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/navigation'
import { VendureService } from '@/services/vendure.service';
import FooterContainer from '@/components/footer/container/FooterContainer';
import { GlobalContextProvider, useGlobalContext } from './store';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  })
{
  const gqService = new VendureService();
  const response: any = await gqService.fetchCollection();
  

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Navigation response={response} />
        {children}
        <div className='pt-3  '>
          <FooterContainer response={response} />
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  )
}
